channels:
    - default
    - conda-forge
dependencies:
    # - nomkl
    - numpy
    - scipy
    - matplotlib
    - h5py
    - pytest
    - jupyter
    - srwpy
    # - libgcc
    - mock
    - sphinx
    - python
    - pytest-profiling
    - autopep8
    - requests
    - pip
    - pip:
        - --no-deps phenom-xfel
